name: ftcontrol
description: View widget in flutter for a app feature control
version: 0.1.1
homepage: https://github.com/gabrielgits/ftcontrol.git
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
